### ISSUE TITLE
removeUnused feature in #6 should not remove imports used by javadoc

### ISSUE THREAD

**Issue by ctubbsii** [revelc/impsort-maven-plugin#7]
Currently, the `removeUnused` feature added in #6 removes any unused imports, as determined by checking identifier tokens in Java code. However, import statements are also used by javadocs to shorten `@see` and `@link` javadoc tags.

The current implementation is too overly aggressive at removing unused imports. Imports used by javadocs should still be considered in-use.

An example project I noticed this on was: https://github.com/apache/accumulo, which contains a lot of javadocs.

**Comment by ctubbsii** [comment]
@tommythorsen wrote on #6:
>  I can take a look at the javadoc issue. Do you have some examples of usages that fail?

See above.

**Comment by Warlord08** [comment]
@ctubbsii quick question - is the removeUnused already implemented, or is waiting on this fix to be fully added to the plugin? Just asking cause I'm unable to find the implementation on the project docs.

**Comment by ctubbsii** [comment]
@Warlord08 The `removeUnused` is already implemented in the current code base (added in #6). It has not been released/published as version 1.1.0, because I was hoping somebody would fix this issue first, so it could be released without this bug.

**Comment by david** [comment]
@ctubbsii any chance the new functionality could be released as a `-SNAPSHOT`? This bug doesn't affect our project (and likely, many others) and the ability to remove unused imports would be welcome.

**Comment by ctubbsii** [comment]
@david "release" and "-SNAPSHOT" are mutually exclusive concepts for Maven repositories, but I can do a new release to include the new feature without this fix. Hopefully we can get this fixed by the release after that.

**Comment by tommythorsen** [comment]
I have been looking into this, and I have some code that is likely to work, except I need a small change to the Javaparser.

@ctubbsii: feel free to assign this bug to me (I wasn't able to assign it to myself).

**Comment by tommythorsen** [comment]
Update: My PR to JavaParser is now merged. I assume it will be available in version 3.6.8. It looks like they release quite often, so it should be available shortly. Once 3.6.8 is available, I will continue working on this.

**Comment by tommythorsen** [comment]
I pushed a PR here: https://github.com/revelc/impsort-maven-plugin/pull/10

It fails now, since version 3.6.8 of JavaParser does not exist, but once the new version of JavaParser is released, it should work. I have tested the change locally.

**Comment by ctubbsii** [comment]
Thanks, @tommythorsen ! GitHub won't let me assign people who don't already have write access to the repo, but that's okay... the PR is enough to indicate it's yours.

**Comment by mttjj** [comment]
Are there any updates on this? I'm hoping this will fix an issue I'm seeing where imports from classes in the same package are not removed since they don't need to be explicitly imported.

```
package com.mttjj.mypackage;

import com.mttjj.mypackage.Foo; // this import can and should be removed

public class Bar {
    public Bar() {
        Foo foo = new Foo();
    }
}
```

```
package com.mttjj.mypackage;

public class Foo {}
```

**Comment by ctubbsii** [comment]
@mttjj That seems to be an unrelated issue. I do not think the PR will fix that. I'm going to try to merge in the PR today, and if it doesn't fix the issue, please create a new one.

**Comment by mttjj** [comment]
Sure. I'll run my tests after your next release (will that be 1.1.1? 1.2.0?) and see if I still see the above behaviour. 

Thank you!

**Comment by ctubbsii** [comment]
We haven't added any new features, so it'll probably be 1.1.1.
